### ISSUE TITLE
Multiplication

### ISSUE THREAD

**Issue by Wdavery** [BENJIGAO/calculator#1]
Hey, awesome app! I was just browsing the creation showcase and this really stood out!

One suggestion for functionality:
Multiplication on a keyboard is usually done with `*` instead of `x` (thanks to the numpad), maybe add that as a shortcut too!

**Comment by BENJIGAO** [comment]
That's a great point! I only have a laptop keyboard so I never even considered a number pad. I will implement it right away (I will remove the 'x' entirely and make multiplication through the keyboard possible only by pressing '*').

Thanks for the suggestion and the compliment as well :)
